# Generated by Django 4.2 on 2023-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		("auth", "0012_alter_user_first_name_max_length"),
	]

	operations = [
		migrations.CreateModel(
			name="User",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("password", models.CharField(max_length=128, verbose_name="password")),
				(
					"last_login",
					models.DateTimeField(
						blank=True, null=True, verbose_name="last login"
					),
				),
				(
					"is_superuser",
					models.BooleanField(
						default=False,
						help_text="Designates that this user has all permissions without explicitly assigning them.",
						verbose_name="superuser status",
					),
				),
				("username", models.CharField(max_length=50)),
				("email", models.EmailField(max_length=254, unique=True)),
				(
					"groups",
					models.ManyToManyField(
						blank=True,
						related_name="users",
						related_query_name="users",
						to="auth.group",
					),
				),
				(
					"user_permissions",
					models.ManyToManyField(
						blank=True,
						related_name="users",
						related_query_name="users",
						to="auth.permission",
					),
				),
			],
			options={
				"abstract": False,
			},
		),
	]
