# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("accounts", "0005_passwordresetcode"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.DeleteModel(
			name="PasswordResetCode",
		),
		migrations.CreateModel(
			name="PasswordResetCode",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("code_hash", models.CharField(max_length=64)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="password_reset_codes",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"indexes": [
					models.Index(fields=["user", "created_at"], name="accounts_pa_user_id_8b0b73_idx"),
					models.Index(fields=["code_hash", "created_at"], name="accounts_pa_code_ha_99f8fe_idx"),
				],
			},
		),
	]
