# Generated by Django 6.0.4 on 2026-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetcode_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
