# Generated by Django 6.0.5 on 2026-05-09 18:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetcode_failed_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshSessionFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=80)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_session_families', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshTokenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('parent_jti', models.CharField(blank=True, db_index=True, max_length=64)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.refreshsessionfamily')),
            ],
        ),
        migrations.AddIndex(
            model_name='refreshsessionfamily',
            index=models.Index(fields=['user', '-last_used_at'], name='accounts_rsf_user_lastused_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshsessionfamily',
            index=models.Index(fields=['revoked_at', 'last_used_at'], name='accounts_rsf_gc_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtokenrecord',
            index=models.Index(fields=['family', 'jti'], name='accounts_rtr_family_jti_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtokenrecord',
            index=models.Index(fields=['family', 'used_at'], name='accounts_rtr_family_used_idx'),
        ),
    ]
