# Generated by Django 6.0.6 on 2026-07-31 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_refreshsessionfamily_refreshtokenrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('transport', models.CharField(choices=[('cookie', 'Cookie'), ('bearer', 'Bearer')], max_length=16)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='refreshsessionfamily',
            name='accounts_rsf_user_lastused_idx',
        ),
        migrations.RemoveIndex(
            model_name='refreshsessionfamily',
            name='accounts_rsf_gc_idx',
        ),
        migrations.RemoveIndex(
            model_name='refreshtokenrecord',
            name='accounts_rtr_family_jti_idx',
        ),
        migrations.RemoveIndex(
            model_name='refreshtokenrecord',
            name='accounts_rtr_family_used_idx',
        ),
        migrations.AddField(
            model_name='devicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='refreshsessionfamily',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refreshtokenrecord',
            name='family',
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['user', '-last_used_at'], name='accounts_ds_user_lastused_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['revoked_at', 'last_used_at'], name='accounts_ds_gc_idx'),
        ),
        migrations.DeleteModel(
            name='RefreshSessionFamily',
        ),
        migrations.DeleteModel(
            name='RefreshTokenRecord',
        ),
    ]
