# Generated by Django 6.0.7 on 2026-08-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_devicesession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(max_length=64, unique=True)),
                ('window_started_at', models.DateTimeField()),
                ('mint_count', models.PositiveSmallIntegerField(default=0)),
                ('guess_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
