"""
Django settings for notif project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
from typing import Any

from notif.config import settings

# Disable throttling during test runs — rate limits would break the test suite.
TESTING = "test" in sys.argv or "pytest" in sys.modules

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings.DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings.DEBUG
DEV_BOOTSTRAP_LOGIN_ENABLED = settings.DEV_BOOTSTRAP_LOGIN_ENABLED
DEV_BOOTSTRAP_USERNAME = settings.DEV_BOOTSTRAP_USERNAME
DEV_BOOTSTRAP_PASSWORD = settings.DEV_BOOTSTRAP_PASSWORD
DEV_BOOTSTRAP_EMAIL = settings.DEV_BOOTSTRAP_EMAIL
DEV_BOOTSTRAP_NAME = settings.DEV_BOOTSTRAP_NAME

ALLOWED_HOSTS = [host.strip() for host in settings.ALLOWED_HOSTS.split(",") if host.strip()]
# Never allow every origin, not even in DEBUG. Combined with CORS_ALLOW_CREDENTIALS
# below, "*" would hand any page a developer happens to visit credentialed access to
# the dev API — and DEV_BOOTSTRAP_LOGIN_ENABLED defaults to DEBUG with a password
# committed to the repo, so that page could log itself in as the dev user.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in settings.CORS_ALLOWED_ORIGINS.split(",") if origin.strip()]
# Dev allowlist: loopback only. A regex rather than a literal list because the
# Flutter web dev server picks a random port on every `flutter run`.
CORS_ALLOWED_ORIGIN_REGEXES = [r"^https?://(localhost|127\.0\.0\.1|\[::1\])(:\d+)?$"] if DEBUG else []
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in settings.CSRF_TRUSTED_ORIGINS.split(",") if origin.strip()]


# Application definition

INSTALLED_APPS = [
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	"corsheaders",
	"rest_framework",
	"rest_framework_simplejwt",
	"drf_spectacular",
	"accounts",
	"monitoring",
	"ops",
]

if DEBUG:
	INSTALLED_APPS += ["silk"]

MIDDLEWARE = [
	"django.middleware.security.SecurityMiddleware",
	"notif.middleware.DevLatencyMiddleware",
	"django.contrib.sessions.middleware.SessionMiddleware",
	"corsheaders.middleware.CorsMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
	MIDDLEWARE.insert(1, "silk.middleware.SilkyMiddleware")

ROOT_URLCONF = "notif.urls"

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
			],
		},
	},
]

WSGI_APPLICATION = "notif.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
	"default": {
		"ENGINE": "django.db.backends.sqlite3",
		"NAME": settings.SQLITE_PATH,
	}
	# 'default': {
	# 	'ENGINE': 'django.db.backends.postgresql',
	# 	'NAME': 'startdb',
	# 	'USER': 'user',
	# 	'PASSWORD': 'root',
	# 	'HOST': 'localhost',  # or '127.0.0.1'
	# 	'PORT': '',  # or '5432'
	# }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

# Note the custom validator
AUTH_PASSWORD_VALIDATORS = [
	{
		"NAME": "notif.password_validators.EntropyValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
		"OPTIONS": {
			"min_length": 8,
		},
	},
	{
		"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
	},
]

AUTH_USER_MODEL = "accounts.User"

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Directory where ``collectstatic`` gathers all static files for production serving.
# In development (runserver), Django serves from each app's ``static/`` dir directly.
# In production, gunicorn/nginx/Caddy serves from this single directory.
STATIC_ROOT = BASE_DIR / settings.STATIC_ROOT
CADDY_ACCESS_LOG_PATH = settings.CADDY_ACCESS_LOG_PATH


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework stuff
_REST_THROTTLE_RATES = {
	"user": "500/hour",
	"anon": "60/min",
	"login": "5/min",
	"register": "3/min",
	# /token/refresh/ is cookie-authenticated, so DRF sees an anonymous caller and
	# keys this scope on the client IP. At 10/min roughly eleven page reloads — or a
	# handful of users behind one NAT/CGNAT — produced 429s, which the client turns
	# into a forced logout. Hammering here buys an attacker nothing: rotation is
	# single-use and a replayed token revokes the whole family, so the rate limit
	# only needs to stop floods. ThrottledTokenRefreshView deliberately drops
	# UserRateThrottle (user = 500/hour ≈ 8/min, also IP-keyed when anonymous) so
	# that this scope is the binding limit rather than dead weight behind it.
	"token_refresh": "60/min",
	"token_verify": "20/min",
	"token_logout": "20/min",
	"client_events": "30/min",
	"password_reset": "3/min",
	"password_reset_confirm": "5/min",
}

REST_FRAMEWORK = {
	"DEFAULT_PERMISSION_CLASSES": [
		"rest_framework.permissions.IsAuthenticated",
	],
	"DEFAULT_AUTHENTICATION_CLASSES": [
		"rest_framework_simplejwt.authentication.JWTAuthentication",
	],
	"DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
	"DEFAULT_THROTTLE_CLASSES": []
	if TESTING
	else [
		"rest_framework.throttling.UserRateThrottle",
		"rest_framework.throttling.AnonRateThrottle",
	],
	"DEFAULT_THROTTLE_RATES": _REST_THROTTLE_RATES,
}

SPECTACULAR_SETTINGS = {
	"TITLE": "Notif API",
	"DESCRIPTION": (
		"Personal update monitoring and notification service.\n\n"
		"Monitors URLs for changes via pluggable scraping strategies "
		"(RSS/Atom feeds, CSS selectors, forum threadmarks, and more)."
	),
	"VERSION": settings.VERSION,
	"SERVE_INCLUDE_SCHEMA": False,
}

# Logs go to stdout/stderr so Docker's json-file driver and systemd's
# journald can capture them. In local dev we additionally write a rotating
# file under backend/logs/ so the user gets persistent logs without
# remembering to pipe runserver through tee.
_log_handlers: dict[str, Any] = {
	"console": {
		"class": "logging.StreamHandler",
		"formatter": "default",
	},
	"system_event": {
		"class": "ops.logging.SystemEventHandler",
		"formatter": "default",
		"level": "WARNING",
	},
}
_root_handlers: list[str] = ["console"]
if not TESTING:
	_root_handlers.append("system_event")

if DEBUG and not TESTING:
	_LOG_DIR = BASE_DIR / "logs"
	_LOG_DIR.mkdir(exist_ok=True)
	_log_handlers["file"] = {
		"class": "logging.handlers.RotatingFileHandler",
		"filename": str(_LOG_DIR / "dev.log"),
		"maxBytes": 5_000_000,
		"backupCount": 3,
		"formatter": "default",
	}
	_root_handlers.append("file")

LOGGING = {
	"version": 1,
	"disable_existing_loggers": False,
	"formatters": {
		"default": {
			"format": "{asctime} {levelname} {name} {message}",
			"style": "{",
		},
	},
	"handlers": _log_handlers,
	"root": {
		"handlers": _root_handlers,
		"level": "DEBUG" if DEBUG else "INFO",
	},
}


if DEBUG:
	# https://stackoverflow.com/questions/18273110/django-make-password-too-slow-for-creating-large-list-of-users-programatically
	# https://docs.djangoproject.com/en/4.2/topics/auth/passwords/
	# This cuts done user creation time from ~270ms to 2.2ms on my laptop, but compromises security.
	PASSWORD_HASHERS = [
		"django.contrib.auth.hashers.MD5PasswordHasher",
		"django.contrib.auth.hashers.PBKDF2PasswordHasher",
		"django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
		"django.contrib.auth.hashers.Argon2PasswordHasher",
		"django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
		"django.contrib.auth.hashers.ScryptPasswordHasher",
	]

if not DEBUG:
	# ── production security hardening ────────────────────────────
	# Redirect all HTTP to HTTPS. Requires a reverse proxy (nginx/Caddy)
	# that sets the X-Forwarded-Proto header.
	SECURE_SSL_REDIRECT = True
	# Tell Django to trust the X-Forwarded-Proto header from the proxy.
	SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
	# Tell browsers to only use HTTPS for this domain for 1 year.
	SECURE_HSTS_SECONDS = 31536000
	SECURE_HSTS_INCLUDE_SUBDOMAINS = True
	# Mark session and CSRF cookies as HTTPS-only — browsers won't send
	# them over plain HTTP.
	SESSION_COOKIE_SECURE = True
	CSRF_COOKIE_SECURE = True


# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
SIMPLE_JWT = {
	"ACCESS_TOKEN_LIFETIME": timedelta(minutes=20 if not DEBUG else 48 * 60),
	"REFRESH_TOKEN_LIFETIME": timedelta(hours=72),
	"LEEWAY": 0,
	# Bearer only. OpenAPI 3 can express exactly one bearerFormat, so listing extra
	# prefixes made drf-spectacular emit a warning on every single view while the
	# generated schema documented "Bearer" anyway. The "JWT" prefix had no client
	# (the Flutter app always sends "Bearer"), and the empty prefix never matched
	# anything: SimpleJWT compares the first space-delimited token of the header
	# against this tuple, so a header with no prefix is rejected regardless.
	"AUTH_HEADER_TYPES": ("Bearer",),
	"AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
	"USER_ID_FIELD": "id",
	"USER_ID_CLAIM": "user_id",
	"SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
	"SLIDING_TOKEN_LIFETIME": timedelta(minutes=20),
	"SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(hours=30),
}

JWT_REFRESH_COOKIE_NAME = "notif_refresh"
# Cookie paths are prefix matches, so this prefix also covers /api/v1/token/verify/,
# which reads its token from the request body and never touches request.COOKIES.
# It is left as-is deliberately: every *other* endpoint under the prefix needs the
# cookie — /token/ (login revokes any pre-existing family), /token/refresh/ and
# /token/logout/ — and there is no cookie-path syntax for "this prefix except one
# child". The alternative, issuing two narrowly-scoped cookies, would double the
# Set-Cookie bookkeeping on every rotation to stop sending the cookie to one
# endpoint that ignores it.
JWT_REFRESH_COOKIE_PATH = "/api/v1/token/"
# Strict, not Lax: the SPA and the API are served from a single origin (see the
# Caddyfile — /api/* and the Flutter bundle share one host), so no legitimate
# cross-site navigation ever needs to carry this cookie.
JWT_REFRESH_COOKIE_SAMESITE = "Strict"
JWT_REFRESH_COOKIE_SECURE = not DEBUG
# How long a just-rotated refresh token may still be replayed. Two everyday events
# replay one: a restored browser session cold-starting several tabs that all hold
# the same cookie, and a rotation that commits server-side while its response is
# lost (container recreated mid-deploy). Inside this window, replaying the direct
# parent of the currently-live token re-issues that live token instead of revoking
# the family; every other replay still trips theft detection.
JWT_REFRESH_ROTATION_GRACE = timedelta(seconds=30)
# Hard ceiling on one refresh session, measured from RefreshSessionFamily.created_at.
# Rotation mints a brand-new token each time, so without this a stolen cookie that
# is refreshed once per REFRESH_TOKEN_LIFETIME would stay valid forever.
JWT_REFRESH_ABSOLUTE_LIFETIME = timedelta(days=30)

# Email
EMAIL_BACKEND = settings.EMAIL_BACKEND or (
	"django.core.mail.backends.smtp.EmailBackend"
	if settings.EMAIL_HOST_PASSWORD
	else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = settings.EMAIL_HOST
EMAIL_PORT = settings.EMAIL_PORT
EMAIL_HOST_USER = settings.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = settings.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = settings.EMAIL_USE_TLS
EMAIL_TIMEOUT = settings.EMAIL_TIMEOUT
DEFAULT_FROM_EMAIL = settings.EMAIL_FROM
SERVER_EMAIL = settings.EMAIL_FROM
EMAIL_FROM = settings.EMAIL_FROM

RESEND_WEBHOOK_SECRET = settings.RESEND_WEBHOOK_SECRET
RESEND_AUDIENCE_ID = settings.RESEND_AUDIENCE_ID

CONFIRM_REDIRECT_URL = settings.CONFIRM_REDIRECT_URL
