[project]
name = 'notif'
requires-python = ">=3.11"

[tool.ruff]
line-length = 120
select = [
	"E",		# pycodestyle
	"F",		# pyflakes
	"UP",		# pyupgrade
	"I",		# isort
	"N",		# pep8-naming
	"ASYNC",	# flake8-async
	"B",		# flake8-bugbear
	"C4",		# flake8-comprehensions
	"DTZ",		# flake8-datetimez
	"DJ",		# flate8-django
	"RET",		# flake8-return
	"SIM",		# flake8-simplify
	"NPY",		# numpy
]
ignore = ["RET501", "RET504"]
exclude = ["**/node_modules",
	"**/__pycache__",
	"**/experimental",
	"**/typestubs",
	"**/migrations",
	"venv",
]


[tool.pyright]
exclude = ["**/node_modules",
	"**/__pycache__",
	"**/experimental",
	"**/typestubs",
	"**/migrations",
	"venv",
]
ignore = []
defineConstant = { DEBUG = true }
stubPath = "stubs"
venv = "venv"

reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.11"
pythonPlatform = "Linux"

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]


[tool.django-stubs]
django_settings_module = "notif.settings"
