[project]
requires-python = ">=3.11"

[tool.ruff]
line-length = 120
select = [
	"E",   # pycodestyle
	"F",   # pyflakes
	"UP",  # pyupgrade
]

[tool.pyright]
exclude = ["**/node_modules",
	"**/__pycache__",
	"**/experimental",
	"**/typestubs",
	"**/migrations",
	"venv",
]
ignore = []
defineConstant = { DEBUG = true }
stubPath = "stubs"
venv = "venv"

reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.11"
pythonPlatform = "Linux"

[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "notif.settings"
