Categories:
  - Internet
AuthorName: Luka Colić
SourceCode: https://github.com/LCEnzo/Notif
IssueTracker: https://github.com/LCEnzo/Notif/issues

Name: Notif
Summary: Personal super app
Description: |-
  Notif collects updates from the sites, feeds and forums it monitors and
  shows them in one place. Also other stuff.
  
  This build talks to https://notif.lcenzo.com.

AutoUpdateMode: None
UpdateCheckMode: None
