# Generated by Django 4.2 on 2023-08-17 21:04

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("monitoring", "0001_initial"),
        ("monitoring", "0002_strategy_link_comparison_info_link_last_scraped_and_more"),
        ("monitoring", "0003_alter_strategy_function"),
        ("monitoring", "0004_alter_strategy_data"),
        ("monitoring", "0005_alter_strategy_data"),
        (
            "monitoring",
            "0006_alter_link_comparison_info_alter_link_last_scraped_and_more",
        ),
    ]

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("strat_cls", models.CharField(choices=[
                    ("GeneralSelectorStrategy", "GeneralSelectorStrategy"),
                    ("SBSVThreadmarksStrategy", "SBSVThreadmarksStrategy"),
                    ("QQAlertsStrategy", "QQAlertsStrategy"),
                    ("KemonoFavouritesStrategy", "KemonoFavouritesStrategy"),
                ], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("comparison_info", models.CharField(blank=True, max_length=262144)),
                ("last_scraped", models.DateTimeField(auto_now=True, null=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_set",
                        to="monitoring.strategy",
                    ),
                ),
            ],
        ),
    ]
