# Generated by Django 4.2 on 2023-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("monitoring", "0002_strategy_link_comparison_info_link_last_scraped_and_more"),
	]

	operations = [
		migrations.AlterField(
			model_name="strategy",
			name="function",
			field=models.CharField(choices=[], default="", max_length=256),
		),
	]
