# Generated by Django 4.2 on 2023-07-09 17:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_alter_strategy_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="data",
            field=models.JSONField(
                default={}, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
