# Generated by Django 5.2.13 on 2026-04-11 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_rename_strategy_function_to_strat_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='strategy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_set', to='monitoring.strategy'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strat_cls',
            field=models.CharField(choices=[('GeneralSelectorStrategy', 'GeneralSelectorStrategy'), ('SBSVThreadmarksStrategy', 'SBSVThreadmarksStrategy'), ('QQAlertsStrategy', 'QQAlertsStrategy'), ('KemonoFavouritesStrategy', 'KemonoFavouritesStrategy')], max_length=256),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('item_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='monitoring.link')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=16)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('update', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='monitoring.update')),
            ],
        ),
    ]
