# Generated by Django 5.2.13 on 2026-04-09 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_rename_strategy_function_to_strat_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='strategy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_set', to='monitoring.strategy'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strat_cls',
            field=models.CharField(choices=[('GeneralSelectorStrategy', 'GeneralSelectorStrategy'), ('SBSVThreadmarksStrategy', 'SBSVThreadmarksStrategy'), ('QQAlertsStrategy', 'QQAlertsStrategy'), ('KemonoFavouritesStrategy', 'KemonoFavouritesStrategy')], max_length=256),
        ),
    ]
