# Generated by Django 5.2.13 on 2026-04-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_link_strategy_alter_strategy_strat_cls_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_scraped',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
