# Generated by Django 5.2.13 on 2026-04-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_link_strategy_alter_strategy_strat_cls'),
        ('monitoring', '0009_alter_link_last_scraped'),
    ]

    operations = [
    ]
