# Generated by Django 6.0.4 on 2026-05-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_merge_20260412_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strat_cls',
            field=models.CharField(choices=[('GeneralSelectorStrategy', 'GeneralSelectorStrategy'), ('SBSVThreadmarksStrategy', 'SBSVThreadmarksStrategy'), ('QQAlertsStrategy', 'QQAlertsStrategy'), ('KemonoFavouritesStrategy', 'KemonoFavouritesStrategy'), ('FeedStrategy', 'FeedStrategy')], max_length=256),
        ),
    ]
