# Generated by Django 6.0.4 on 2026-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_strategy_strat_cls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strat_cls',
            field=models.CharField(choices=[('GeneralSelectorStrategy', 'General Selector'), ('SBSVThreadmarksStrategy', 'SB/SV Threadmarks'), ('QQAlertsStrategy', 'QQ Alerts'), ('KemonoFavouritesStrategy', 'Kemono Favourites'), ('FeedStrategy', 'RSS')], max_length=256),
        ),
    ]
