# Generated by Django 6.0.4 on 2026-05-05 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_alter_strategy_strat_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_scrape_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='link',
            name='next_scrape_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='scrape_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='scrape_failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='scrape_interval_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
