# Generated by Django 6.0.7 on 2026-08-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owners(apps, schema_editor):
    """Adopt existing strategies: the owner is the user of the first link
    that references the strategy. Truly orphaned strategies (no links) stay
    ownerless and become invisible through the API — their `data` field may
    hold third-party credentials, so nobody gets them by default."""
    Strategy = apps.get_model("monitoring", "Strategy")
    Link = apps.get_model("monitoring", "Link")
    for strategy in Strategy.objects.filter(owner__isnull=True).iterator():
        first_link = Link.objects.filter(strategy=strategy).order_by("pk").first()
        if first_link is not None:
            strategy.owner = first_link.user
            strategy.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_link_last_scrape_error_link_next_scrape_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owners, migrations.RunPython.noop),
    ]
