# Generated by Django 6.0.7 on 2026-08-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owners(apps, schema_editor):
    """Adopt existing strategies and split shared ones.

    Every strategy becomes owner-only: the owner is the user of the first
    referencing link. If *other* users also reference the strategy, each of
    them gets their own copy (same class + data) and their links are
    re-pointed to it — so nobody keeps read/update access to somebody else's
    stored credentials. Truly orphaned strategies (no links) stay ownerless
    and are visible to nobody."""
    Strategy = apps.get_model("monitoring", "Strategy")
    Link = apps.get_model("monitoring", "Link")
    for strategy in Strategy.objects.filter(owner__isnull=True).order_by("pk").iterator():
        user_ids = list(
            Link.objects.filter(strategy=strategy)
            .order_by("user_id")
            .values_list("user_id", flat=True)
            .distinct()
        )
        if not user_ids:
            continue
        primary, *others = user_ids
        strategy.owner_id = primary
        strategy.save(update_fields=["owner"])
        for user_id in others:
            copy = Strategy.objects.create(
                strat_cls=strategy.strat_cls,
                data=strategy.data,
                owner_id=user_id,
            )
            Link.objects.filter(strategy=strategy, user_id=user_id).update(strategy=copy)


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_link_last_scrape_error_link_next_scrape_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_owners, migrations.RunPython.noop),
    ]
