# Generated by Django 6.0.5 on 2026-07-03 14:21

from django.db import migrations


def backfill_strategy_user(apps, schema_editor):
    """Assign an owner to every existing strategy before ``user`` becomes non-null.

    A strategy's owner is the user of any link that references it. Orphan
    strategies (no links) fall back to the first superuser, then the first user.
    Any strategy left without a possible owner (empty user table) is deleted so
    the subsequent non-null AlterField cannot fail.
    """
    Strategy = apps.get_model("monitoring", "Strategy")
    User = apps.get_model("accounts", "User")

    fallback = User.objects.filter(is_superuser=True).order_by("pk").first() or User.objects.order_by("pk").first()

    for strategy in Strategy.objects.filter(user__isnull=True):
        link = strategy.link_set.order_by("pk").first()
        owner = link.user if link is not None else fallback
        if owner is None:
            strategy.delete()
            continue
        strategy.user = owner
        strategy.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_strategy_user'),
    ]

    operations = [
        migrations.RunPython(backfill_strategy_user, migrations.RunPython.noop),
    ]
