# Generated by Django 6.1.1 on 2026-10-08 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_origin', models.CharField(max_length=255)),
                ('recording_method', models.CharField(choices=[('unknown', 'Unknown'), ('actively_recorded', 'Actively recorded'), ('automatically_recorded', 'Automatically recorded'), ('manual_entry', 'Manual entry')], max_length=32)),
                ('device_type', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('watch', 'Watch'), ('phone', 'Phone'), ('scale', 'Scale'), ('ring', 'Ring'), ('head_mounted', 'Head mounted'), ('fitness_band', 'Fitness band'), ('chest_strap', 'Chest strap'), ('smart_display', 'Smart display')], max_length=32)),
                ('device_manufacturer', models.CharField(blank=True, max_length=255)),
                ('device_model', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('data_origin', 'recording_method', 'device_type', 'device_manufacturer', 'device_model'), name='health_source_unique'), models.CheckConstraint(condition=models.Q(models.Q(('device_type', ''), _negated=True), models.Q(('device_manufacturer', ''), ('device_model', '')), _connector='OR'), name='health_source_no_device_details_without_device')],
            },
        ),
        migrations.CreateModel(
            name='HealthAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('steps_count_total', 'StepsRecord.COUNT_TOTAL (count)'), ('sleep_duration_total', 'SleepSessionRecord.SLEEP_DURATION_TOTAL (ms)')], max_length=32)),
                ('bucket_start_ms', models.BigIntegerField()),
                ('value', models.BigIntegerField(null=True)),
                ('data_origins', models.JSONField(default=list)),
                ('computed_at_ms', models.BigIntegerField()),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'metric', 'bucket_start_ms'), name='health_aggregate_owner_metric_bucket_unique')],
            },
        ),
        migrations.CreateModel(
            name='HealthDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_id', models.UUIDField()),
                ('observed_at_ms', models.BigIntegerField()),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'hc_id'), name='health_deletion_owner_hc_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='HealthIngestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('coverage_start_ms', models.BigIntegerField(null=True)),
                ('record_count', models.PositiveIntegerField()),
                ('deletion_count', models.PositiveIntegerField()),
                ('aggregate_hour_count', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'received_at'], name='health_batch_owner_received')],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_id', models.UUIDField()),
                ('record_type', models.CharField(choices=[('steps', 'Steps'), ('resting_heart_rate', 'Resting heart rate'), ('sleep_session', 'Sleep session')], max_length=32)),
                ('start_ms', models.BigIntegerField()),
                ('start_offset_s', models.IntegerField(null=True)),
                ('end_ms', models.BigIntegerField(null=True)),
                ('end_offset_s', models.IntegerField(null=True)),
                ('last_modified_ms', models.BigIntegerField()),
                ('payload', models.JSONField()),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='health.healthsource')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'record_type', 'start_ms'], name='health_record_type_start')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'hc_id'), name='health_record_owner_hc_id_unique'), models.CheckConstraint(condition=models.Q(('end_ms__isnull', True), ('end_ms__gt', models.F('start_ms')), _connector='OR'), name='health_record_end_after_start')],
            },
        ),
    ]
