# Generated by Django 6.0.4 on 2026-05-05 20:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('source', models.CharField(db_index=True, max_length=120)),
                ('kind', models.CharField(db_index=True, max_length=80)),
                ('message', models.CharField(max_length=1000)),
                ('details', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='ops_systeme_created_05a06a_idx'), models.Index(fields=['level', '-created_at'], name='ops_systeme_level_58567e_idx'), models.Index(fields=['source', '-created_at'], name='ops_systeme_source_29bee4_idx')],
            },
        ),
    ]
