# Generated by Django 6.0.4 on 2026-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLock',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField()),
            ],
        ),
    ]
